packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  msw: false

catalogs:
  clsx:
    clsx: 2.1.1
  cva:
    class-variance-authority: 0.7.1
  daisy5:
    daisyui: 5.5.19
  date-fns:
    date-fns: 4.1.0
  eslint9:
    '@eslint/js': 9.39.2
    '@eslint/eslintrc': 3.3.3
    '@next/eslint-plugin-next': 15.3.5
    '@typescript-eslint/parser': 8.50.1
    '@typescript-eslint/eslint-plugin': 8.50.1
    eslint: 9.39.4
    eslint-config-next: 15.3.5
    eslint-config-prettier: 10.1.8
    eslint-config-only-warn: 1.1.0
    eslint-plugin-neverthrow: 1.1.4
    eslint-plugin-only-warn: 1.1.0
    eslint-plugin-react: 7.37.5
    eslint-plugin-react-hooks: 7.0.1
    eslint-plugin-turbo: 2.7.1
    globals: 16.5.0
    typescript-eslint: 8.50.1
  exceljs:
    exceljs: "4.4.0"
  jsdom:
    jsdom: 29.0.1
  lucide:
    lucide-react: 1.7.0
  msw:
    msw: 2.12.14
  next-router-mock:
    "next-router-mock": 1.0.5
  next16:
    next: 16.2.1
    next-themes: 0.4.6
  node24:
    '@types/node': 24.0.11
    node: 24.16.0
  pino:
    pino: 10.3.1
  react-aria-components:
    react-aria-components: 1.16.0
  react19:
    "@types/react": 19.2.14
    "@types/react-dom": 19.2.3
    react: 19.2.4
    react-dom: 19.2.4
  tailwind-merge:
    tailwind-merge: 3.5.0
  tanstack:
    "@tanstack/react-form": 1.28.6
    "@tanstack/react-query": 5.96.0
    "@tanstack/react-table": 8.21.3
  testing-library:
    "@testing-library/jest-dom": 6.9.1
    "@testing-library/react": 16.3.2
    "@testing-library/user-event": 14.6.1
  typescript5:
    typescript: 5.8.3
  typescript6:
    typescript: 6.0.2
  vite:
    vite: 8.0.3
  vitest:
    "@vitest/coverage-v8": 4.1.2
    vitest: 4.1.2
  whatwg-fetch:
    "whatwg-fetch": 3.6.20
  zod:
    zod: 4.3.6
